### ISSUE TITLE
Unable to discover app or find running task

### ISSUE THREAD

**Issue by Astrovic** [tidev/vscode-titanium#1118] opened 2023-04-20 16:36 UTC
### Describe the Bug
I'm trying to use the Debugging function. When the simulator is launched, one of this error message appears.

![error2](https://user-images.githubusercontent.com/2573811/233430987-0fcc8818-1709-437c-bc5b-6c37adba716b.png)

![error](https://user-images.githubusercontent.com/2573811/233429205-b96bd4fb-330a-4b22-94e4-b6aee0dad1cc.png)

This is my launch.json
```js
{
    "version": "0.2.0",
    "configurations": [
    
        {
            "name": "Launch on Android",
            "type": "titanium",
            "request": "launch",
            "platform": "android"
        },
        {
            "name": "Launch on iOS",
            "type": "titanium",
            "request": "launch",
            "platform": "ios"
        }
    ]
}
```

### Steps to reproduce the Bug
From the extension, I choose the simulator from the list and click on the debug icon. After the build process, the simulator and the app are launched correctly, but then the error message appears.

### Your Environment
| Software | Version |
| ---------------- | ---------- |
| Titanium SDK |11.1.1.GA |
| Titanium CLI |6.1.1 |
| Alloy CLI |2.0.2 |
| VS Code | 1.77.3|
| vscode-titanium | 1.1.0|

### Logs
```
******** Unhandled error in debug adapter - Unhandled promise rejection: {"code":-32601,"message":"'Debugger' domain was not found","data":[{"code":-32601,"message":"'Debugger' domain was not found"}]}
Error processing "launch": 'Runtime' domain was not found: [object Object]
```

**Comment by ewanharris** [comment] 2023-04-20 19:52
It looks like the socket we need to use to connect to the iOS simulator has changed, will investigate this further and see what changes are needed. Sadly there's not workaround for this right now :/

**Comment by ewanharris** [comment] 2023-04-20 22:58
Confirmed this to be an SDK issues so closing this issue.

Opened https://github.com/tidev/titanium_mobile/pull/13812 to demonstrate a potential fix but needs someone more knowledgeable in iOS to finish it of most likely

**Closed by ewanharris** 2023-04-20 22:58 UTC
Labels: bug

**Comment by Astrovic** [comment] 2023-04-21 07:37
Well, thanks for your quick checkout. I will try your PR.
